### PR TITLE
adding support for filter operation

### PR DESCRIPTION
**Pull request by daniel-sc**
Support for the filter operation - see: https://developers.podio.com/doc/items/filter-items-4496747

### CODE REVIEW

**Comment by daniel-sc** [comment]
Hello - is there anyone maintaining this repository??

**Comment by cmchase** [comment]
I'm sorry, Daniel, with some internal team changes we lost sight of the public clients a bit. I'm not knowledgable of Java, but I'm going to merge your PR since you've contributed in the past.

Sorry for the confusion and thanks for your patience. I'll bring this oversight up in our next team meeting.

**Comment by daniel-sc** [comment]
@cmchase: thanks. I'd be nice if you'd assure someone is watching the clients (if not even develop further) and at least do merges and cut new releases!

**Comment by cmchase** [comment]
I agree. We're discussing our options and, at the very least, need to work out "ownership" for things like merging PRs from active contributors like yourself.

Thanks again for your patience.

**Pull request merged**
