### PR TITLE
Some changes to keep up-to-date with the podio API

### PR DESCRIPTION
**Pull request by PetrF0X**
I added an ApplicationViewType.STREAM because of an Exception which said ApplicationViewType.STREAM wasn't found while mapping when trying to get an Application by appAPI.getApp(appId). Hope this helps.

### CODE REVIEW

**Comment by PetrF0X** [comment]
The particular error says:
Caused by:
org.codehaus.jackson.map.JsonMappingException: No enum constant com.podio.app.ApplicationViewType.STREAM (through reference chain: com.podio.app.Application["config"]->com.podio.app.ApplicationConfiguration["default_view"])

So I added the enum constant and will see if it helps.
Thanks in advance.

**Comment by PetrF0X** [comment]
I just tested it and it works. So can you please merge?

**Comment by PetrF0X** [comment]
Now I added some more changes. This time to the ContactAPI. One thing is an enum ContactType in order to make possible getting the space contacts. Because this switch was missing and the default value was "user" so there was no chance to get space contacts.
The other thing is updating the Profile with some address fields in order to provide full Profile as it is in docs on https://developers.podio.com/doc/contacts.
And one more thing: I faced a situation when no try to get a Profile of a contact ended succesfully. So I looked a bit in documentation and found that the getContact() method is now working under version 2, so I added this "/v2" into the address in this method. As well as I renamed the field to profileId as it really is a profileId that is taken as a parameter.

Please have a look at it. I tested everything so I think there is no need not to merge.

Thanks, Petr

**Comment by albertfdp** [comment]
Hi @PetrF0X I'll take a look and merge it

**Comment by albertfdp** [comment]
Merged!

**Pull request merged**
