### PR TITLE
Implemented a way how to watch the current api usage (rate limits)

### PR DESCRIPTION
**Pull request by PetrF0X**
It was a problem for me to watch the api usage (get the data from http headers). Finally I figured it out and here it is. I couldn't think of any concept how to save the data and I didn't need to store them. So I just look at the integers and print them out after every api call. If you have any idea how to make it better and more useful, please tell me.

### CODE REVIEW

**Comment by PetrF0X** [comment]
Hi @holm, can you please have a look at this and maybe provide me with an idea how to make it designed properly?

**Comment by PetrF0X** [comment]
Hello @albertfdp, I was thinking about it and finally I came to a decision that it would be the best if there was a base object called e. g. RateLimits which would all the classes that can be returned extend.
What do you think about this approach?

**Comment by albertfdp** [comment]
The current approach seems fine for me: I am happy to merge it to master. What are you looking to achieve with what you are proposing now?

**Comment by PetrF0X** [comment]
I'm glad that you accept the current approach.
With this approach the information about the rate limits is decoupled from the returned data. I was thinking if it could be a problem if there was e.g. tens or hundreds of requests per second. The information about the current usage would not be connected to the data so I could maybe warn wrong user about his limit.

I'd be glad if you merged this pull request. We can talk about the other approach later on.

**Comment by daniel-sc** [comment]
Does this account for response where the headers are not set? 
If I remember correctly for `PodioFile::get_raw` the headers are not set ..

**Comment by PetrF0X** [comment]
@daniel-sc 
I'm not familiar with any API call where these headers are not set. But your point is great, if there was such a call, current code would throw a NullPointerException.
I will make another commit which will fix this, soon. Thank you!

**Comment by albertfdp** [comment]
@daniel-sc  :+1: Yes, and some clients do not have rate limit, so the absence of such might be in all requests. Thanks @PetrF0X !

**Comment by PetrF0X** [comment]
@albertfdp  @daniel-sc Please have a look at the added code
Thanks

**Comment by daniel-sc** [comment]
looks fine!

**Comment by PetrF0X** [comment]
@albertfdp Hello, can you please merge this?

**Comment by albertfdp** [comment]
Done!

**Pull request merged**
